# Standard Kotlin utilities that get carried over from year to year.

load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library")

kt_jvm_library(
    name = "common",
    srcs = glob(["*.kt"]),
    visibility = ["//visibility:public"],
    deps = [
    ],
)
