/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.knottysoftware.exercises.adventofcode2022

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun appHasAGreeting() {
        // Nope
    }
}
