package com.knottysoftware.exercises.adventofcode2024

import com.knottysoftware.exercises.adventofcode.runner.RunPuzzleWithInput
import com.knottysoftware.exercises.adventofcode.runner.RunPuzzleWithText

fun main(args: Array<String>) {
    val sample = """
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
    """
    //RunPuzzleWithText(::Day8b, sample)
    RunPuzzleWithInput(::Day8b, 2024, 8)
}
